# Generated by Django 5.1.5 on 2025-01-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_priority_task_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='rating',
        ),
    ]
